[package]
name = "adventofcode_2015"
version = "0.1.0"
edition = "2021"
author = ["Dinesh Kumar"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"

[[bin]]
name = "aoc"
path = "src/main.rs"